# Generated by Django 5.1.5 on 2025-02-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='id',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='job',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='id',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='job',
        ),
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_required',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
