# Generated by Django 5.1.5 on 2025-03-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_rename_name_interest_interest_interest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='interest',
            field=models.CharField(max_length=255),
        ),
    ]
