# Generated by Django 5.1.5 on 2025-03-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_interest_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
    ]
