# Generated by Django 5.1.5 on 2025-03-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_rename_name_job_titleeeee_remove_job_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='titleeeee',
            new_name='name',
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
    ]
