# Generated by Django 5.1.5 on 2025-03-04 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_rename_titleeeee_job_name_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='name',
        ),
    ]
