# Generated by Django 5.1.5 on 2025-02-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='fee',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='program',
            name='duration_weeks',
        ),
        migrations.RemoveField(
            model_name='program',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='program',
            name='seats_available',
        ),
        migrations.RemoveField(
            model_name='program',
            name='start_date',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='internship_company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
