# Generated by Django 5.1.5 on 2025-02-22 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_rename_fee_program_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='payment_status',
        ),
    ]
