# Generated by Django 5.1.5 on 2025-02-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_remove_enrollment_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='sale_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
