# Generated by Django 5.1.5 on 2025-02-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_details', '0002_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallink',
            old_name='name',
            new_name='platform',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
