# Generated by Django 5.1.5 on 2025-02-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_enrollmentorder_verificationorder_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='only_one_amount_instance')],
            },
        ),
    ]
