# Generated by Django 5.1.4 on 2025-03-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="city",
            old_name="name",
            new_name="namee",
        ),
    ]
