# Generated by Django 5.1.5 on 2025-02-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='id',
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='user',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
