# Generated by Django 5.1.5 on 2025-02-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_emailotp_id_alter_emailotp_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailotp',
            old_name='user',
            new_name='email',
        ),
    ]
