# Generated by Django 5.1.5 on 2025-02-12 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_account_father_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('college_name', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('college_city', models.CharField(max_length=255)),
                ('passing_year', models.IntegerField(max_length=4)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('college_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_educations', to='accounts.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
