# Generated by Django 5.1.5 on 2025-02-12 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_education_passing_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='name',
        ),
    ]
