# Generated by Django 5.1.5 on 2025-02-12 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_education_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='otp',
            field=models.CharField(blank=True, default=None, max_length=4, null=True),
        ),
    ]
