# Generated by Django 5.1.5 on 2025-02-13 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_account_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth_city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='current_city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_cities', to='accounts.state')),
            ],
        ),
    ]
