# Generated by Django 5.1.5 on 2025-02-13 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_account_birth_city_alter_account_current_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birth_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_born_users', to='accounts.city'),
        ),
        migrations.AlterField(
            model_name='account',
            name='current_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_users', to='accounts.city'),
        ),
    ]
