# Generated by Django 5.1.5 on 2025-02-13 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_account_birth_city_account_current_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='college_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_educations', to='accounts.city'),
        ),
    ]
