# Generated by Django 5.1.5 on 2025-02-18 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_passwordresetotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
    ]
