# Generated by Django 5.1.3 on 2025-03-05 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_account_career_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='full_name',
            new_name='full_nameeeeee',
        ),
    ]
