# Generated by Django 5.1.3 on 2025-03-08 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_rename_full_nameeeeee_account_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='full_name',
            new_name='full_nameeee',
        ),
    ]
