# Generated by Django 5.1.3 on 2025-03-08 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_rename_full_name_account_full_nameeee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='full_nameeee',
            new_name='full_name',
        ),
    ]
